(function(ui){
	ui.lang = {
			CONFIRM_ITEM_SUPPRESSION : 'Etes-vous sur de vouloir supprimer l\'élément ?'
			,CONFIRM_ITEM_DUPPLICATION : 'Etes-vous sur de vouloir duppliquer l\'élément ?' 			
			,POST_BACK_MODIFIED 		:' a été modifié avec succès'
			,POST_BACK_DELETED 		:' a été supprimé avec succès'
			,POST_BACK_ADDED 			:' a été ajouté avec succès'
			,POST_BACK_DUPLICATED 	:' a été dupliqué avec succès'			
			,VALIDATION_DATA_REQUIRED:'Champ obligatoire' 
			,VALIDATION_DATA_LIMIT : 'Max Caractères'			
			,CONFIRM_DATA_LOST:'===========\n -- ATTENTION -- \n les données insérées vont etre perdu !\n vouliez vous continuer ?'
			,UNVALID_URL:'Adresse web non valide'
			,UNVALID_LINK:'Lien non valide'
			,UNVALID_INTEGER:'Chiffre non valide'
			,UNVALID_FLOAT:'Chiffre avec fraction non valide'
			,UNVALID_PRICE:'Prix non valide'
			,UNVALID_TEXT:'Caractère non valide'
			,UNVALID_ZIPCODE : 'Code postal non valide'
			,UNVALID_EMAIL :'E-Mail non valide'
			,UNVALID_PHONE :'Téléphone non valide'
			,UNVALID_PASSWORD_PATTERN :'Mot de passe non valide (7-16 Caractère chifre, _ , commencer par une lettre)'
			,UNVALID_DATE_FORMAT : 'Date none valide (ex: jj/mm/aaaa ou jj-mm-aaaa)'
			,UNVALID_COLOR_FORMAT : 'Couleur non valide (ex: #AAA ou #A1C1F9)'			
			,ERROR_DELTING_FILE:'Erreur lors de la suppression de fichier'			
			,FILE_UPLOAD:{
					"BrowserNotSupported" : 'Navigateur non compatible'
					,"TooManyFiles":'Nombre de fichier trop élevé'
					 ,"FileTooLarge":'Fichier trop grande'
					 ,"FileTypeNotAllowed":'Type de fichier interdit'
					 ,"NotFound":'[FU_404] Fichier introuvable'
					 , "NotReadable":'[FU_304] Fichier non accessible'
					 , "AbortError":'[FU_577] Erreur '
					 , "ReadError" : '[FU_578] Erreur '
			}		
	}	
}(UI))
